-- ============================================
-- ORDER ITEM PRODUCT ID
-- Adds a short, human-typeable, unique code to each order item for the
-- QR label + ops lookup. The UUID `id` stays the immutable internal PK
-- (referenced by FKs in intake_items, consigned_intakes, raffles, etc.);
-- `product_id` is a decoupled secondary code we can regenerate on
-- collision and print on labels.
--
-- Format: 9-char Crockford Base32 (no I/L/O/U) -> ~35 trillion combos,
-- survives being hand-typed off a smudged label. Generated by a BEFORE
-- INSERT trigger so every insert path gets one automatically.
--
-- NOTE: `product_id` is NOT a foreign key to any products table — it is a
-- self-contained label code. Named to match the team's "product number"
-- vocabulary.
-- ============================================

-- ----- 1. column (nullable for backfill, tightened below) -----
ALTER TABLE order_items ADD COLUMN product_id TEXT;

COMMENT ON COLUMN order_items.product_id IS
  'Short unique label/QR code (9-char Crockford Base32). Not a FK; see migration 20260606.';

-- ----- 2. generator: 9 random Crockford Base32 chars -----
-- Crockford alphabet excludes I, L, O, U to avoid read/typo confusion.
-- random() is fine here: uniqueness is guaranteed by the retry loop +
-- unique index below, not by the RNG quality.
CREATE OR REPLACE FUNCTION gen_product_id() RETURNS TEXT AS $$
DECLARE
  alphabet CONSTANT TEXT := '0123456789ABCDEFGHJKMNPQRSTVWXYZ';
  result TEXT := '';
  i INT;
BEGIN
  FOR i IN 1..9 LOOP
    result := result || substr(alphabet, floor(random() * 32)::int + 1, 1);
  END LOOP;
  RETURN result;
END;
$$ LANGUAGE plpgsql VOLATILE;

-- ----- 3. trigger: assign a unique product_id on insert -----
-- Loops until the candidate is unused. The unique index (step 6) is the
-- ultimate backstop for the astronomically rare same-instant concurrent
-- collision (two inserts picking the same code before either commits).
CREATE OR REPLACE FUNCTION set_order_item_product_id() RETURNS TRIGGER AS $$
DECLARE
  candidate TEXT;
BEGIN
  IF NEW.product_id IS NOT NULL THEN
    RETURN NEW;
  END IF;
  LOOP
    candidate := gen_product_id();
    EXIT WHEN NOT EXISTS (SELECT 1 FROM order_items WHERE product_id = candidate);
  END LOOP;
  NEW.product_id := candidate;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- ----- 4. backfill existing rows -----
DO $$
DECLARE
  r RECORD;
  candidate TEXT;
BEGIN
  FOR r IN SELECT id FROM order_items WHERE product_id IS NULL LOOP
    LOOP
      candidate := gen_product_id();
      EXIT WHEN NOT EXISTS (SELECT 1 FROM order_items WHERE product_id = candidate);
    END LOOP;
    UPDATE order_items SET product_id = candidate WHERE id = r.id;
  END LOOP;
END $$;

-- ----- 5. tighten: required going forward -----
ALTER TABLE order_items ALTER COLUMN product_id SET NOT NULL;

-- ----- 6. uniqueness guarantee + lookup index -----
CREATE UNIQUE INDEX idx_order_items_product_id ON order_items(product_id);

-- ----- 7. wire up the trigger -----
CREATE TRIGGER trg_order_items_product_id
  BEFORE INSERT ON order_items
  FOR EACH ROW
  EXECUTE FUNCTION set_order_item_product_id();
