-- ============================================
-- TRIAGE CODE
-- Human-readable short code for triage_packages — the package-level
-- identifier we print/scan when an inbound package can't be matched to an
-- order (reused/invalid shipping label). Counterpart to
-- order_items.product_id (migration 20260606), but for the *pre-order*
-- state where no order_item exists yet.
--
-- Format: 'T-' + 8 Crockford Base32 chars (no I/L/O/U), e.g. T-7Q3KM9XP.
-- The 'T-' prefix makes it self-identifying for ops AND lets scanners
-- discriminate triage vs product codes by prefix ('-' can't appear in a
-- product_id). Generated by a BEFORE INSERT trigger; unique + NOT NULL.
-- ============================================

-- ----- 1. column (nullable for backfill, tightened below) -----
ALTER TABLE triage_packages ADD COLUMN triage_code TEXT;

COMMENT ON COLUMN triage_packages.triage_code IS
  'Human-readable package code: ''T-'' + 8 Crockford Base32 chars. QR + label. See migration 20260607.';

-- ----- 2. generator: 'T-' + 8 Crockford Base32 chars -----
CREATE OR REPLACE FUNCTION gen_triage_code() RETURNS TEXT AS $$
DECLARE
  alphabet CONSTANT TEXT := '0123456789ABCDEFGHJKMNPQRSTVWXYZ';
  result TEXT := 'T-';
  i INT;
BEGIN
  FOR i IN 1..8 LOOP
    result := result || substr(alphabet, floor(random() * 32)::int + 1, 1);
  END LOOP;
  RETURN result;
END;
$$ LANGUAGE plpgsql VOLATILE;

-- ----- 3. trigger: assign a unique triage_code on insert -----
CREATE OR REPLACE FUNCTION set_triage_code() RETURNS TRIGGER AS $$
DECLARE
  candidate TEXT;
BEGIN
  IF NEW.triage_code IS NOT NULL THEN
    RETURN NEW;
  END IF;
  LOOP
    candidate := gen_triage_code();
    EXIT WHEN NOT EXISTS (SELECT 1 FROM triage_packages WHERE triage_code = candidate);
  END LOOP;
  NEW.triage_code := candidate;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- ----- 4. backfill existing rows -----
DO $$
DECLARE
  r RECORD;
  candidate TEXT;
BEGIN
  FOR r IN SELECT id FROM triage_packages WHERE triage_code IS NULL LOOP
    LOOP
      candidate := gen_triage_code();
      EXIT WHEN NOT EXISTS (SELECT 1 FROM triage_packages WHERE triage_code = candidate);
    END LOOP;
    UPDATE triage_packages SET triage_code = candidate WHERE id = r.id;
  END LOOP;
END $$;

-- ----- 5. tighten: required going forward -----
ALTER TABLE triage_packages ALTER COLUMN triage_code SET NOT NULL;

-- ----- 6. uniqueness guarantee + lookup index -----
CREATE UNIQUE INDEX idx_triage_packages_triage_code ON triage_packages(triage_code);

-- ----- 7. wire up the trigger -----
CREATE TRIGGER trg_triage_packages_code
  BEFORE INSERT ON triage_packages
  FOR EACH ROW
  EXECUTE FUNCTION set_triage_code();
